FROM python:3.9
RUN apt-get clean && apt-get update
WORKDIR /app
RUN pip install gunicorn==20.1.0 
COPY requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir
COPY . .
CMD ["gunicorn", "--bind", "0.0.0.0:8080", "backend.wsgi"]

# FROM python:3.9
# WORKDIR /app
# COPY requirements.txt .
# RUN pip install -r requirements.txt --no-cache-dir
# COPY . .
# CMD ["python", "manage.py", "runserver", "0:8080"] 

RUN apt-get clean && apt-get update